// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_aSaBfRS8EcWH5Nrfm5hvfzKg3Nv7fE',
    appId: '1:106550536020:web:96de9a414bd50a5f774ac1',
    messagingSenderId: '106550536020',
    projectId: 'flutter-fire-cli-demo',
    authDomain: 'flutter-fire-cli-demo.firebaseapp.com',
    storageBucket: 'flutter-fire-cli-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEoCzwdHBEOpBqdIvzhVPa936JlzPcb4',
    appId: '1:106550536020:android:93bb409a8eb28585774ac1',
    messagingSenderId: '106550536020',
    projectId: 'flutter-fire-cli-demo',
    storageBucket: 'flutter-fire-cli-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN-59aKfNd9UMIWklyE4aQwlT6l7GABBk',
    appId: '1:106550536020:ios:0a67277e15d56e2c774ac1',
    messagingSenderId: '106550536020',
    projectId: 'flutter-fire-cli-demo',
    storageBucket: 'flutter-fire-cli-demo.appspot.com',
    iosClientId: '106550536020-6gp6prtvmkkhnd3prh0ccpohl8f570kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfire.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN-59aKfNd9UMIWklyE4aQwlT6l7GABBk',
    appId: '1:106550536020:ios:0a67277e15d56e2c774ac1',
    messagingSenderId: '106550536020',
    projectId: 'flutter-fire-cli-demo',
    storageBucket: 'flutter-fire-cli-demo.appspot.com',
    iosClientId: '106550536020-6gp6prtvmkkhnd3prh0ccpohl8f570kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfire.flutterfire',
  );
}
