# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
   desc "Increment the version from the latest relase"
   lane :increment_firebase_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:106550536020:android:93bb409a8eb28585774ac1"
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  end
  desc "Submit a new Beta Build to firebase distribution"
  lane :beta do
    gradle(task: "clean")
    increment_firebase_version
    gradle(task: "assemble", build_type: "Release")
    firebase_app_distribution(
                app: "1:106550536020:android:93bb409a8eb28585774ac1",
                firebase_cli_token:"1//0gmsHqa6c4_CNCgYIARAAGBASNwF-L9IrORHPF7V5pgsKCmZzAd3c2GeB2lx0EhNUaCG7w-CggeKS3QzC63b6hWvYKyU9Flv0C_c",
                testers: "suganyadevi.r@oclocksoftware.com",
                release_notes: "New firebase version",
                android_artifact_path:"/Users/ocsmac-44/Documents/flutterfire/build/app/outputs/flutter-apk/app-release.apk"
            )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
